name: Sync GitHub to Notion

on:
  push:
    branches:
      - main   # Change if your branch is named differently
  issues:
    types: [opened]
  pull_request:
    types: [opened, closed]

jobs:
  update-notion:
    runs-on: ubuntu-latest
    steps:
      - name: Send update to Notion
        run: |
          PAYLOAD=$(jq -n \
            --arg msg "${{ github.event.head_commit.message }}" \
            --arg url "${{ github.event.head_commit.url }}" \
            --arg date "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
            '{
              parent: { database_id: env.NOTION_DATABASE_ID },
              properties: {
                Name: { title: [{ text: { content: $msg } }] },
                "GitHub Link": { url: $url },
                Date: { date: { start: $date } }
              }
            }')
          
          curl -X POST "https://api.notion.com/v1/pages" \
            -H "Authorization: Bearer $NOTION_TOKEN" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            -d "$PAYLOAD"
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
